# Generated by Django 5.1.4 on 2025-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wttapp', '0002_alter_workday_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='lastname',
        ),
        migrations.AddField(
            model_name='workday',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
