# Generated by Django 5.1.5 on 2025-01-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wttapp", "0003_remove_workday_firstname_remove_workday_lastname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workday",
            name="name",
        ),
    ]
