# Generated by Django 5.1.5 on 2025-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wttapp", "0004_remove_workday_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
