# Generated by Django 5.1.5 on 2025-02-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("noticeboard", "0002_rename_author_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="post",
        ),
    ]
