# Generated by Django 5.1.4 on 2025-01-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_remove_userprofile_department_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Former', 'Former')], default='Active', help_text='User status (Active or Former).', max_length=10),
        ),
    ]
