# Generated by Django 5.1.5 on 2025-02-09 05:02

import UserLogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserLogin", "0003_userprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=UserLogin.models.user_profile_picture_path,
            ),
        ),
    ]
