# Generated by Django 5.1.5 on 2025-02-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserLogin", "0004_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
